Ioctl error path fixes
versity/scoutfs-kmod-dev pull request #46
Opened 2020-12-02 18:27 UTC by agrover

A couple fixes for some error paths in ioctl handling.

2020-12-02 19:39 UTC, zabbo requested changes
Can we get much better commit descriptions that describe why we're making these changes?  I'm guessing the list/lock changes were made by seeing that use and free of each didn't quite line up, but missed that it was always safe to free.

In general, I think the pattern of having resources initialized such that they're safe to free so that we can have one exit path that tries to tear down everything safely is better than having to perfectly balance the state buildup and where to go to tear down.  We should aim for the safe teardown when we can.  (So the srch rb_root isn't great, but your fix is nice and minimal.. it doesn't span a bunch of additional state buildup/freeing).   So I think we can drop the list/lock changes and keep the rb_root as a nice minimal fix.

2020-12-02 19:39 UTC, zabbo commented on src/ioctl.c
>  	scoutfs_srch_destroy_rb_root(&sroot);
This makes sense, I like this :).

2020-12-02 19:39 UTC, zabbo commented on src/ioctl.c
>  	scoutfs_dir_free_backref_path(sb, &list);
I don't think this is needed because the list is initialized and empty.  It's always safe to try and free it.

2020-12-02 19:39 UTC, zabbo commented on src/ioctl.c
>  	scoutfs_unlock(sb, lock, SCOUTFS_LOCK_WRITE);
And I don't think this is needed because the lock is NULL if it's unlocked and _unlock will not have a problem with it.

2020-12-02 23:46 UTC, agrover commented
Hey, thanks for the comments. I'll go ahead and drop the last two commits. My one remaining question is, instead of the first commit I think we could just zero-initialize `sroot` and the destroy would become a no-op. Slightly preferable?

2020-12-03 01:18 UTC, zabbo commented
> Hey, thanks for the comments. I'll go ahead and drop the last two commits. My one remaining question is, instead of the first commit I think we could just zero-initialize `sroot` and the destroy would become a no-op. Slightly preferable?

Sure, either's fine with me, including doing the least work and keeping your original fix :).  I do like your idea of getting safe cleanup by initializign to null without having to export the init function.  We could also do the pattern where we define a DECLARE_SRCH_RBROOT macro in srch.h and have it initialize the fields.  But whatever you prefer, I think they're all fine sets of trade-offs.

2020-12-03 01:30 UTC, agrover commented
OK let's just merge this PR as is. I'll pull the trigger tomorrow if you don't beat me to it.

2020-12-03 17:02 UTC, zabbo approved these changes

2020-12-03 17:02 UTC, merged